// <auto-generated />
using LocalBusiness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusiness.Migrations
{
    [DbContext(typeof(LocalBusinessContext))]
    [Migration("20220121195820_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LocalBusiness.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("County")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("State")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Category = "Southern",
                            City = "Kennesaw",
                            County = "Cobb",
                            Name = "Cracker Barrel",
                            Price = 3,
                            Rating = 3,
                            Review = "Great place to eat",
                            State = "GA",
                            StreetAddress = "3389 Busbee Dr NW",
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 2,
                            Category = "American Diner",
                            City = "Marietta",
                            County = "Cobb",
                            Name = "Marietta Diner",
                            Price = 3,
                            Rating = 5,
                            Review = "Excellent food and quality service",
                            State = "GA",
                            StreetAddress = "306 Cobb Parkway S",
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 3,
                            Category = "BBQ",
                            City = "Adairsville",
                            County = "Bartow",
                            Name = "Character's Famous BBQ",
                            Price = 2,
                            Rating = 5,
                            Review = "Excellent BBQ in a small town, featured on BBQ Pit Wars and BBQ Pitmasters",
                            State = "GA",
                            StreetAddress = "6419 Joe Frank Harris Pkwy",
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 4,
                            Category = "American",
                            City = "Marietta",
                            County = "Cobb",
                            Name = "Three Dollar Cafe",
                            Price = 3,
                            Rating = 4,
                            Review = "The best wings around Atlanta, also good beer selection",
                            State = "GA",
                            StreetAddress = "3000 Windy Hill Road, Suite 132",
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 5,
                            Category = "American",
                            City = "Atlanta",
                            County = "Fulton",
                            Name = "The Vortex",
                            Price = 3,
                            Rating = 4,
                            Review = "One of the best burger joints in Atlanta with an adult comedy theme",
                            State = "GA",
                            StreetAddress = "438 Moreland Ave NE",
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 6,
                            Category = "Fast Food",
                            City = "Adairsville",
                            County = "Bartow",
                            Name = "Wendy's",
                            Price = 1,
                            Rating = 1,
                            Review = "Unfriendly staff and your order is rarely correct, avoid if you can",
                            State = "GA",
                            StreetAddress = "957 Highway 140 W",
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 7,
                            Category = "Southern Breakfast",
                            City = "Marietta",
                            County = "Cobb",
                            Name = "The Red Eyed Mule",
                            Price = 3,
                            Rating = 4,
                            Review = "Mouth melting breakfast food at a reasonable price",
                            State = "GA",
                            StreetAddress = "430 South Marietta Pkwy SE",
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 8,
                            Category = "BBQ",
                            City = "Atlanta",
                            County = "Fulton",
                            Name = "Fat Matt's Rib Shack",
                            Price = 3,
                            Rating = 5,
                            Review = "The best ribs and BBQ in Atlanta!",
                            State = "GA",
                            StreetAddress = "1811 Piedmont Ave NE",
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 9,
                            Category = "Watches",
                            City = "Kennesaw",
                            County = "Cobb",
                            Name = "Watch Shop",
                            Price = 3,
                            Rating = 4,
                            Review = "Decent selection of watches, great repair shop!",
                            State = "GA",
                            StreetAddress = "504 Tick Tock Pkwy",
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 10,
                            Category = "Antiques",
                            City = "Marietta",
                            County = "Cobb",
                            Name = "Full of Things",
                            Price = 4,
                            Rating = 5,
                            Review = "Unique items, all in good shape, be prepared to spend a lot",
                            State = "GA",
                            StreetAddress = "374 Antique Rd",
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 11,
                            Category = "Hats",
                            City = "Dallas",
                            County = "Paulding",
                            Name = "Hat House",
                            Price = 2,
                            Rating = 3,
                            Review = "Decent selection of hats and lower than average prices",
                            State = "GA",
                            StreetAddress = "Mall Blvd",
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 12,
                            Category = "Shoes",
                            City = "Tucker",
                            County = "Dekalb",
                            Name = "Shoes R Us",
                            Price = 4,
                            Rating = 2,
                            Review = "Limited selection and high prices, last time I'm shopping here",
                            State = "GA",
                            StreetAddress = "A Mall Somewhere Rd",
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 13,
                            Category = "Guitars",
                            City = "Roswell",
                            County = "Fulton",
                            Name = "Righteous Guitars",
                            Price = 3,
                            Rating = 5,
                            Review = "Friend and helpful staff, great selection of guitars",
                            State = "GA",
                            StreetAddress = "1455 Hembree Rd",
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 14,
                            Category = "Thrift Store",
                            City = "Adairsville",
                            County = "Bartow",
                            Name = "A Local Thrift Store",
                            Price = 1,
                            Rating = 3,
                            Review = "It's a thrift store",
                            State = "GA",
                            StreetAddress = "Strip Mall Plaza",
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 15,
                            Category = "Furniture",
                            City = "Marietta",
                            County = "Cobb",
                            Name = "Can't Believe It's Not Real Wood Furniture",
                            Price = 2,
                            Rating = 3,
                            Review = "No false advertising here",
                            State = "GA",
                            StreetAddress = "Somewhere In China St",
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 16,
                            Category = "Clothing",
                            City = "Atlanta",
                            County = "Fulton",
                            Name = "Clothing Store 101",
                            Price = 5,
                            Rating = 5,
                            Review = "The finest clothing money can buy, pretty sure I saw a celebrity buy something so I bought it too",
                            State = "GA",
                            StreetAddress = "999 Everywhere St",
                            Type = "Shop"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
